"""phase 12.5 backtest_runs table

Revision ID: 01000768212e
Revises: c87469ee23d2
Create Date: 2026-05-01 16:47:56.378713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01000768212e'
down_revision: Union[str, None] = 'c87469ee23d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('universe_json', sa.JSON(), nullable=False),
    sa.Column('date_range_start', sa.String(length=10), nullable=False),
    sa.Column('date_range_end', sa.String(length=10), nullable=False),
    sa.Column('initial_capital_quote', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('final_equity_quote', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('slippage_config_json', sa.JSON(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('equity_curve_path', sa.String(length=512), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('ran_at', sa.DateTime(), nullable=False),
    sa.Column('ran_by_actor', sa.String(length=64), nullable=False),
    sa.Column('runtime_seconds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_runs_ran_at', ['ran_at'], unique=False)
        batch_op.create_index('ix_backtest_runs_strategy_ran', ['strategy_id', 'ran_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_backtest_runs_strategy_ran')
        batch_op.drop_index('ix_backtest_runs_ran_at')

    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
