"""phase 10.1 trading_state.mode column

Revision ID: 0cfeddebb20c
Revises: 2bed420134e7
Create Date: 2026-05-01 00:00:14.771753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfeddebb20c'
down_revision: Union[str, None] = '2bed420134e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=16), server_default='off', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_state', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
