"""phase_8_3_risk

Revision ID: 198604252fc8
Revises: 31bc3cf60425
Create Date: 2026-04-28 11:04:21.253691

Adds:
- ``trading_state`` (singleton, CHECK id=1). Seeded with operator-
  approved defaults: enabled=False, daily_dd_max_pct=0.03 (3%),
  total_dd_max_pct=0.25 (25%). Any change to these defaults requires
  a strategic-session decision and a follow-up migration.
- ``risk_decisions`` (append-only). Composite UNIQUE(signal_id, version)
  ensures concurrent appends with the same version fail at the DB
  level — the repository's append helper retries with the new version.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198604252fc8'
down_revision: Union[str, None] = '31bc3cf60425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_dd_max_pct', sa.Float(), nullable=False),
    sa.Column('total_dd_max_pct', sa.Float(), nullable=False),
    sa.Column('killed_until', sa.DateTime(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified_by', sa.String(length=64), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_trading_state_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('gate_results_json', sa.JSON(), nullable=False),
    sa.Column('sized_amount_quote', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_risk_decisions_version_positive'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'version', name='uq_risk_decisions_signal_version')
    )
    with op.batch_alter_table('risk_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_risk_decisions_signal_id', ['signal_id'], unique=False)

    # ### end Alembic commands ###

    # Seed the singleton trading_state row with operator-approved defaults.
    # FASE 8.3 invariant: enabled stays False until FASE 14 LIVE; daily DD
    # 3% and total DD 25% are signed defaults.
    op.execute(
        "INSERT INTO trading_state "
        "(id, enabled, daily_dd_max_pct, total_dd_max_pct, killed_until, "
        " last_modified_at, last_modified_by) "
        "VALUES (1, 0, 0.03, 0.25, NULL, CURRENT_TIMESTAMP, 'migration:phase_8_3_risk')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_decisions_signal_id')

    op.drop_table('risk_decisions')
    op.drop_table('trading_state')
    # ### end Alembic commands ###
