"""phase 11.4 daily_postmortems table

Revision ID: 286685a8a10b
Revises: 50eeec809023
Create Date: 2026-05-01 00:40:11.492552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286685a8a10b'
down_revision: Union[str, None] = '50eeec809023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_postmortems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_utc', sa.String(length=10), nullable=False),
    sa.Column('trades_analyzed', sa.Integer(), nullable=False),
    sa.Column('aggregate_pnl_quote', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('patterns_json', sa.JSON(), nullable=False),
    sa.Column('outliers_json', sa.JSON(), nullable=False),
    sa.Column('suggestions_json', sa.JSON(), nullable=False),
    sa.Column('regime_summary', sa.Text(), nullable=True),
    sa.Column('ai_provider_used', sa.String(length=16), nullable=True),
    sa.Column('ai_model_used', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_utc', name='uq_daily_postmortems_date_utc')
    )
    with op.batch_alter_table('daily_postmortems', schema=None) as batch_op:
        batch_op.create_index('ix_daily_postmortems_date_utc', ['date_utc'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_postmortems', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_postmortems_date_utc')

    op.drop_table('daily_postmortems')
    # ### end Alembic commands ###
