"""phase 9.5 reconciler

Revision ID: 2bed420134e7
Revises: 2cb89b917d99
Create Date: 2026-04-30 16:17:15.434140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bed420134e7'
down_revision: Union[str, None] = '2cb89b917d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('quote_currency', sa.String(length=8), nullable=False),
    sa.Column('equity_quote', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('balances_json', sa.JSON(), nullable=False),
    sa.Column('positions_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_snapshots_taken_at', ['taken_at'], unique=False)

    op.create_table('reconcile_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('triggered_by', sa.String(length=64), nullable=False),
    sa.Column('orphan_exchange_count', sa.Integer(), nullable=False),
    sa.Column('orphan_db_count', sa.Integer(), nullable=False),
    sa.Column('balance_drift_count', sa.Integer(), nullable=False),
    sa.Column('discrepancies_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('portfolio_snapshot_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('ok', 'discrepancies', 'error')", name='ck_reconcile_runs_status'),
    sa.ForeignKeyConstraint(['portfolio_snapshot_id'], ['portfolio_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconcile_runs', schema=None) as batch_op:
        batch_op.create_index('ix_reconcile_runs_started_at', ['started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reconcile_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_reconcile_runs_started_at')

    op.drop_table('reconcile_runs')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_snapshots_taken_at')

    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
