"""phase_9_4_trades

Revision ID: 2cb89b917d99
Revises: e279afe3d929
Create Date: 2026-04-30 16:06:22.714274

Adds:
- ``trades`` (append-only with status cache + UNIQUE on signal_id)
- ``trade_status_events`` (event log)
- FK ``orders.trade_id -> trades.id``. The column was created in
  9.2's migration as plain Integer specifically so we could add the
  FK here once ``trades`` exists. Downgrade drops the FK first
  (otherwise the parent table can't be dropped).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb89b917d99'
down_revision: Union[str, None] = 'e279afe3d929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('size', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('take_profit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('realized_pnl_quote', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('fees_paid_quote', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exchange_id', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.CheckConstraint("side IN ('long', 'short')", name='ck_trades_side'),
    sa.CheckConstraint("status IN ('pending', 'open', 'closed', 'failed')", name='ck_trades_status'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', name='uq_trades_signal_id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('ix_trades_closed_at', ['closed_at'], unique=False, sqlite_where=sa.text('closed_at IS NOT NULL'))
        batch_op.create_index(batch_op.f('ix_trades_status'), ['status'], unique=False)
        batch_op.create_index('ix_trades_status_opened_at', ['status', 'opened_at'], unique=False)

    op.create_table('trade_status_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_status_events', schema=None) as batch_op:
        batch_op.create_index('ix_trade_status_events_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_trade_status_events_trade_id', ['trade_id'], unique=False)

    # FK orders.trade_id -> trades.id (column was plain Integer NULL
    # since 9.2 specifically to allow this backfill).
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_orders_trade_id_trades',
            'trades',
            ['trade_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the FK first so trades can be dropped after.
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_trade_id_trades', type_='foreignkey')

    with op.batch_alter_table('trade_status_events', schema=None) as batch_op:
        batch_op.drop_index('ix_trade_status_events_trade_id')
        batch_op.drop_index('ix_trade_status_events_created_at')

    op.drop_table('trade_status_events')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trades_status_opened_at')
        batch_op.drop_index(batch_op.f('ix_trades_status'))
        batch_op.drop_index('ix_trades_closed_at', sqlite_where=sa.text('closed_at IS NOT NULL'))

    op.drop_table('trades')
    # ### end Alembic commands ###
