"""phase_8_1_signal_lifecycle

Revision ID: 31bc3cf60425
Revises: 4aa51675ba88
Create Date: 2026-04-28 10:36:07.377278

Adds:
- ``signals.expires_at`` (TIMESTAMP nullable, indexed). Default TTL is
  ``generated_at + 4 × timeframe_bars`` computed at insert time by the
  repository.
- ``signal_status_events`` table (append-only event log). Tracks every
  transition of ``signals.status``. Per ROADMAP.md Parte 0 mandate:
  ``signals.status`` is now a denormalised cache of the latest event,
  mutated only via :meth:`SignalRepository.transition`.

Backfill applied: any pre-existing ``signals`` row with
``status='pending'`` gets ``expires_at = generated_at + 4 hours``
(safe default for the typical 1h timeframe). Without this, the first
run of ``expire_stale_signals_job`` would flood-expire historical
pending rows that pre-date the TTL contract.

Events tracking begins at this migration; no backfill of historical
events for pre-migration signals — they simply have no events recorded.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31bc3cf60425'
down_revision: Union[str, None] = '4aa51675ba88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_status_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_status_events', schema=None) as batch_op:
        batch_op.create_index('ix_signal_status_events_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_signal_status_events_signal_id', ['signal_id'], unique=False)

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_signals_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###

    # Backfill: any pending signal predating this migration gets a
    # 4-hour default TTL relative to its generation time, so the first
    # tick of the expire job does not flood-expire historical rows.
    op.execute(
        "UPDATE signals "
        "SET expires_at = datetime(generated_at, '+4 hours') "
        "WHERE status = 'pending' AND expires_at IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_expires_at'))
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('signal_status_events', schema=None) as batch_op:
        batch_op.drop_index('ix_signal_status_events_signal_id')
        batch_op.drop_index('ix_signal_status_events_created_at')

    op.drop_table('signal_status_events')
    # ### end Alembic commands ###
