"""initial_schema_all_tables

Revision ID: 3eb7476b3325
Revises: 
Create Date: 2026-04-22 20:16:30.313622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb7476b3325'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_calls_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_calls_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_calls_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_calls_timestamp'), ['timestamp'], unique=False)

    op.create_table('cache',
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('value', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cache_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cache_source'), ['source'], unique=False)

    op.create_table('processed_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processed_news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_news_processed_at'), ['processed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_news_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_news_url_hash'), ['url_hash'], unique=True)

    op.create_table('sent_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sent_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sent_alerts_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sent_alerts_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_sent_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('source_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_calls_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_calls_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_calls_timestamp'), ['timestamp'], unique=False)

    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.String(length=1), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("operator IN ('>', '<')", name='ck_price_alert_operator'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_alerts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_alerts_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_watchlist_user_ticker')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_items_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_items_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_items_ticker'))

    op.drop_table('watchlist_items')
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_price_alerts_ticker'))
        batch_op.drop_index(batch_op.f('ix_price_alerts_is_active'))

    op.drop_table('price_alerts')
    op.drop_table('users')
    with op.batch_alter_table('source_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_calls_timestamp'))
        batch_op.drop_index(batch_op.f('ix_source_calls_success'))
        batch_op.drop_index(batch_op.f('ix_source_calls_source'))

    op.drop_table('source_calls')
    with op.batch_alter_table('sent_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sent_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_sent_alerts_ticker'))
        batch_op.drop_index(batch_op.f('ix_sent_alerts_sent_at'))

    op.drop_table('sent_alerts')
    with op.batch_alter_table('processed_news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_news_url_hash'))
        batch_op.drop_index(batch_op.f('ix_processed_news_ticker'))
        batch_op.drop_index(batch_op.f('ix_processed_news_processed_at'))

    op.drop_table('processed_news')
    with op.batch_alter_table('cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cache_source'))
        batch_op.drop_index(batch_op.f('ix_cache_expires_at'))

    op.drop_table('cache')
    with op.batch_alter_table('ai_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_calls_timestamp'))
        batch_op.drop_index(batch_op.f('ix_ai_calls_task_type'))
        batch_op.drop_index(batch_op.f('ix_ai_calls_success'))
        batch_op.drop_index(batch_op.f('ix_ai_calls_provider'))

    op.drop_table('ai_calls')
    # ### end Alembic commands ###
