"""phase_7_signals_table

Revision ID: 4aa51675ba88
Revises: 3eb7476b3325
Create Date: 2026-04-27 23:52:23.973290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa51675ba88'
down_revision: Union[str, None] = '3eb7476b3325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('entry_low', sa.Float(), nullable=False),
    sa.Column('entry_high', sa.Float(), nullable=False),
    sa.Column('invalidation', sa.Float(), nullable=False),
    sa.Column('target_1', sa.Float(), nullable=False),
    sa.Column('target_2', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('indicators_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('confidence_ai', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("side IN ('long', 'short', 'flat')", name='ck_signals_side'),
    sa.CheckConstraint("status IN ('pending', 'expired', 'consumed', 'cancelled')", name='ck_signals_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_status'), ['status'], unique=False)
        batch_op.create_index('ix_signals_strategy_generated', ['strategy_id', 'generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_ticker'))
        batch_op.drop_index('ix_signals_strategy_generated')
        batch_op.drop_index(batch_op.f('ix_signals_status'))

    op.drop_table('signals')
    # ### end Alembic commands ###
