"""phase 11.3 news_reactions table

Revision ID: 50eeec809023
Revises: 30738afb34b2
Create Date: 2026-05-01 00:33:50.624084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50eeec809023'
down_revision: Union[str, None] = '30738afb34b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_url_hash', sa.String(length=64), nullable=False),
    sa.Column('news_headline', sa.String(length=512), nullable=False),
    sa.Column('news_sentiment', sa.Float(), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('position_trade_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('ai_provider_used', sa.String(length=16), nullable=True),
    sa.Column('ai_model_used', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("decision IN ('reduce', 'close', 'hold')", name='ck_news_reactions_decision'),
    sa.ForeignKeyConstraint(['position_trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_reactions', schema=None) as batch_op:
        batch_op.create_index('ix_news_reactions_ticker_decided_at', ['ticker', 'decided_at'], unique=False)
        batch_op.create_index('ix_news_reactions_url_hash', ['news_url_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_reactions', schema=None) as batch_op:
        batch_op.drop_index('ix_news_reactions_url_hash')
        batch_op.drop_index('ix_news_reactions_ticker_decided_at')

    op.drop_table('news_reactions')
    # ### end Alembic commands ###
