"""phase 11.5 ai_validations table

Revision ID: c87469ee23d2
Revises: 286685a8a10b
Create Date: 2026-05-01 00:45:39.026078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87469ee23d2'
down_revision: Union[str, None] = '286685a8a10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_validations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('provider_used', sa.String(length=16), nullable=True),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('request_hash', sa.String(length=32), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('approve', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_validations', schema=None) as batch_op:
        batch_op.create_index('ix_ai_validations_provider_decided', ['provider_used', 'decided_at'], unique=False)
        batch_op.create_index('ix_ai_validations_signal_decided', ['signal_id', 'decided_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_validations', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_validations_signal_decided')
        batch_op.drop_index('ix_ai_validations_provider_decided')

    op.drop_table('ai_validations')
    # ### end Alembic commands ###
