"""phase 14 go_live_pendings + wind_down_state tables

Revision ID: d982b7619ed3
Revises: dac2069b3f27
Create Date: 2026-05-01 23:04:33.091214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd982b7619ed3'
down_revision: Union[str, None] = 'dac2069b3f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('go_live_pendings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pending_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('initiated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'expired', 'rejected')", name='ck_go_live_pendings_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pending_id', name='uq_go_live_pendings_pending_id')
    )
    with op.batch_alter_table('go_live_pendings', schema=None) as batch_op:
        batch_op.create_index('ix_go_live_pendings_initiated_at', ['initiated_at'], unique=False)

    op.create_table('wind_down_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('started_by', sa.String(length=64), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('positions_at_start', sa.Integer(), nullable=False),
    sa.Column('positions_remaining_last_check', sa.Integer(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wind_down_state')
    with op.batch_alter_table('go_live_pendings', schema=None) as batch_op:
        batch_op.drop_index('ix_go_live_pendings_initiated_at')

    op.drop_table('go_live_pendings')
    # ### end Alembic commands ###
