"""phase 13.2 critical_incidents table

Revision ID: dac2069b3f27
Revises: 01000768212e
Create Date: 2026-05-01 17:22:12.236760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac2069b3f27'
down_revision: Union[str, None] = '01000768212e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('critical_incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('auto_detected', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name='ck_critical_incidents_severity'),
    sa.CheckConstraint("type IN ('reconcile.orphan_unresolved', 'reconcile.balance_unattributed', 'circuit_breaker.open_over_15min', 'executor.stop_missing_post_fill', 'risk.kill_switch_daily_dd', 'ops.manual_intervention', 'reconcile.failed_over_30min')", name='ck_critical_incidents_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('critical_incidents', schema=None) as batch_op:
        batch_op.create_index('ix_critical_incidents_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index('ix_critical_incidents_type_occurred', ['type', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critical_incidents', schema=None) as batch_op:
        batch_op.drop_index('ix_critical_incidents_type_occurred')
        batch_op.drop_index('ix_critical_incidents_occurred_at')

    op.drop_table('critical_incidents')
    # ### end Alembic commands ###
