"""phase_9_2_orders

Revision ID: e279afe3d929
Revises: 198604252fc8
Create Date: 2026-04-30 15:41:05.516956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e279afe3d929'
down_revision: Union[str, None] = '198604252fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=64), nullable=True),
    sa.Column('exchange_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('raw_payload_json', sa.JSON(), nullable=False),
    sa.Column('raw_response_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("side IN ('buy', 'sell')", name='ck_orders_side'),
    sa.CheckConstraint("type IN ('limit', 'market', 'stop_market', 'stop_limit')", name='ck_orders_type'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', name='uq_orders_client_order_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_exchange_order_id', ['exchange_order_id'], unique=False, sqlite_where=sa.text('exchange_order_id IS NOT NULL'))
        batch_op.create_index('ix_orders_signal_id_created_at', ['signal_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('order_status_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_status_events', schema=None) as batch_op:
        batch_op.create_index('ix_order_status_events_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_order_status_events_order_id', ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_status_events', schema=None) as batch_op:
        batch_op.drop_index('ix_order_status_events_order_id')
        batch_op.drop_index('ix_order_status_events_created_at')

    op.drop_table('order_status_events')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index('ix_orders_signal_id_created_at')
        batch_op.drop_index('ix_orders_exchange_order_id', sqlite_where=sa.text('exchange_order_id IS NOT NULL'))

    op.drop_table('orders')
    # ### end Alembic commands ###
