"""phase 10.2 mode_transitions table

Revision ID: f9ce7c25e1cc
Revises: 0cfeddebb20c
Create Date: 2026-05-01 00:04:17.181406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ce7c25e1cc'
down_revision: Union[str, None] = '0cfeddebb20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mode_transitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_mode', sa.String(length=16), nullable=False),
    sa.Column('to_mode', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('transitioned_at', sa.DateTime(), nullable=False),
    sa.Column('override_used', sa.Boolean(), nullable=False),
    sa.Column('mode_started_at_after_transition', sa.DateTime(), nullable=False),
    sa.CheckConstraint("from_mode IN ('off', 'shadow', 'paper', 'semi_auto', 'live')", name='ck_mode_transitions_from_mode'),
    sa.CheckConstraint("to_mode IN ('off', 'shadow', 'paper', 'semi_auto', 'live')", name='ck_mode_transitions_to_mode'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mode_transitions', schema=None) as batch_op:
        batch_op.create_index('ix_mode_transitions_to_mode_transitioned_at', ['to_mode', 'transitioned_at'], unique=False)
        batch_op.create_index('ix_mode_transitions_transitioned_at_desc', ['transitioned_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mode_transitions', schema=None) as batch_op:
        batch_op.drop_index('ix_mode_transitions_transitioned_at_desc')
        batch_op.drop_index('ix_mode_transitions_to_mode_transitioned_at')

    op.drop_table('mode_transitions')
    # ### end Alembic commands ###
